# Generated by Django 3.0.5 on 2020-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='user fname')),
                ('last_name', models.CharField(max_length=40, verbose_name='user fname')),
                ('address', models.CharField(max_length=200, verbose_name='user address')),
                ('mobile', models.IntegerField(max_length=10, verbose_name='user mobile ')),
                ('email', models.CharField(max_length=60, verbose_name='user email')),
                ('organisation', models.CharField(max_length=100, verbose_name='user organisation')),
                ('desgination', models.CharField(max_length=50, verbose_name='user designation')),
            ],
        ),
    ]
