# Generated by Django 3.0.5 on 2020-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='interval',
            field=models.CharField(max_length=50, verbose_name='website interval'),
        ),
    ]
