# Generated by Django 3.0.5 on 2020-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200412_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_checked_time',
            field=models.CharField(default='', max_length=100, verbose_name='website lastchecked'),
        ),
        migrations.AddField(
            model_name='website',
            name='loadtime',
            field=models.CharField(default='', max_length=5, verbose_name='website loadtime'),
        ),
        migrations.AddField(
            model_name='website',
            name='uptime',
            field=models.CharField(default='', max_length=5, verbose_name='website uptime'),
        ),
    ]
